query About($slug: String!) {
	about(filter: { slug: { eq: $slug } }) {
		...AboutFragment
	}
}

query AllAbouts {
	abouts: allAbouts(first: 100) {
		...AboutFragment
	}
}

query AllAboutsMenu {
	abouts: allAbouts(first: 100) {
		title
		slug
	}
}

fragment AboutFragment on AboutRecord {
	__typename
	_modelApiKey
	id
	title
	intro
	slug
	image {
		...ImageFragment
	}
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
			}
			... on ButtonRecord {
				__typename
				id
				text
				url
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_seoMetaTags {
		attributes
		content
		tag
	}
}
