query Commission($slug: String!) {
	commission(filter: { slug: { eq: $slug } }) {
		...CommissionFragment
	}
}

query AllCommissions($first: IntType = 10, $skip: IntType = 0, $regionId: ItemId) {
	commissions: allCommissions(
		filter: { region: { eq: $regionId } }
		orderBy: [year_DESC]
		first: $first
		skip: $skip
	) {
		...CommissionLightFragment
	}
	pagination: _allCommissionsMeta(filter: { region: { eq: $regionId } }) {
		count
	}
}

query AllCommissionsMenu {
	commissions: allCommissions(first: 100) {
		title
		slug
	}
}

query AllCommissionCategories {
	commissionCategories: allCommissionCategories(first: 100) {
		id
		title
	}
}

query LatestCommissions($first: IntType = 2, $skip: IntType = 0, $regionId: ItemId) {
	commissions: allCommissions(
		filter: { region: { eq: $regionId } }
		orderBy: [createdAt_DESC]
		first: $first
		skip: $skip
	) {
		...CommissionLightFragment
	}
}

query RelatedCommissions(
	$first: IntType = 6
	$skip: IntType = 0
	$regionId: ItemId
	$commissionId: ItemId
) {
	commissions: allCommissions(
		filter: { region: { eq: $regionId }, id: { neq: $commissionId } }
		first: $first
		skip: $skip
	) {
		...CommissionLightFragment
	}
}

fragment CommissionFragment on CommissionRecord {
	__typename
	_modelApiKey
	id
	title
	intro
	slug
	city
	year
	artist
	consultant
	work
	commissioner
	blackHeadline
	image {
		...ImageFragment
	}
	category {
		id
		title
	}
	content {
		... on ImageRecord {
			__typename
			id
			image {
				...ImageFragment
			}
		}
		... on VideoRecord {
			__typename
			id
			title
			video {
				height
				width
				title
				provider
				providerUid
				thumbnailUrl
				url
			}
		}
		... on RecordInterface {
			__typename
			id
		}
	}
	region {
		...RegionFragment
	}
	_seoMetaTags {
		attributes
		content
		tag
	}
}

fragment CommissionLightFragment on CommissionRecord {
	__typename
	_modelApiKey
	id
	title
	slug
	city
	year
	artist
	consultant
	blackHeadline
	image {
		...ImageThumbnailFragment
	}
	category {
		id
		title
	}
	region {
		...RegionFragment
	}
}
