query Consult($slug: String!) {
	consult(filter: { slug: { eq: $slug } }) {
		...ConsultFragment
	}
}

query AllConsults {
	consults: allConsults(first: 100) {
		...ConsultFragment
	}
}

query AllConsultsMenu {
	consults: allConsults(first: 100) {
		title
		slug
	}
}

query AllConsultants {
	consultants: allConsultants(first: 100) {
		id
		email
		name
		title
	}
}

fragment ConsultFragment on ConsultRecord {
	__typename
	_modelApiKey
	id
	title
	intro
	slug
	image {
		...ImageFragment
	}
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
			}
			... on ButtonRecord {
				__typename
				id
				text
				url
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_seoMetaTags {
		attributes
		content
		tag
	}
}

fragment ConsultLightFragment on ConsultRecord {
	__typename
	id
	title
	intro
	slug
	image {
		...ImageFragment
	}
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
			}
			... on ButtonRecord {
				__typename
				id
				text
				url
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
}
