fragment ForArtistFragment on ForArtistRecord {
	id
	createdAt
	content {
		value
		blocks {
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on ButtonRecord {
				__typename
				id
				text
				url
			}
		}
	}
	image {
		...ImageThumbnailFragment
	}
	slug
	title
	intro
}

query AllForArtist {
	forArtists: allForArtists(orderBy: [createdAt_DESC], first: 100) {
		id
		createdAt
		slug
		title
	}
	pagination: _allForArtistsMeta {
		count
	}
}

query ForArtist($slug: String!) {
	forArtist(filter: { slug: { eq: $slug } }) {
		...ForArtistFragment
	}
}
