query AllMembers($regionId: ItemId, $first: IntType = 10, $skip: IntType = 0) {
	members: allMembers(filter: { region: { eq: $regionId } }, first: $first, skip: $skip) {
		...MemberLightFragment
	}
	pagination: _allMembersMeta(filter: { region: { eq: $regionId } }) {
		count
	}
}
query AllMembersList($regionId: ItemId, $first: IntType = 10, $skip: IntType = 0) {
	members: allMembers(filter: { region: { eq: $regionId } }, first: $first, skip: $skip) {
		fullName
		firstName
		lastName
		image {
			id
		}
		active
		slug
		region {
			...RegionFragment
		}
	}
	pagination: _allMembersMeta(filter: { region: { eq: $regionId } }) {
		count
	}
}

query AllMembersWithPortfolio($regionId: ItemId, $first: IntType = 10, $skip: IntType = 0) {
	members: allMembers(
		filter: { image: { exists: true }, active: { eq: true }, region: { eq: $regionId } }
		orderBy: _createdAt_DESC
		first: $first
		skip: $skip
	) {
		...MemberLightFragment
	}
	pagination: _allMembersMeta(
		filter: { image: { exists: true }, active: { eq: true }, region: { eq: $regionId } }
	) {
		count
	}
}

query AllMembersCities {
	cities: allMembers(
		filter: { image: { exists: true }, active: { eq: true }, city: { isBlank: false } }
	) {
		name: city
	}
}

query Member($email: String!) {
	member(filter: { email: { matches: { pattern: $email, caseSensitive: false } } }) {
		...MemberFragment
	}
}
query MemberBySlug($slug: String!) {
	member(filter: { slug: { eq: $slug } }) {
		...MemberFragment
	}
}

query MemberByPasswordToken($token: String!) {
	member(filter: { resettoken: { eq: $token } }) {
		...MemberFragment
	}
}

query AllMemberCategories {
	memberCategories: allMemberCategories {
		id
		categoryType
	}
}

query ApplyForMembership {
	apply {
		id
		title
		intro
		image {
			...ImageFragment
		}
		content {
			value
			blocks {
				... on ButtonRecord {
					__typename
					id
					text
					url
				}
			}
		}
	}
}

query MemberNews($slug: String!) {
	memberNews(filter: { slug: { eq: $slug } }) {
		...MemberNewsFragment
	}
}
query MemberNewsById($id: ItemId!) {
	memberNews(filter: { id: { eq: $id } }) {
		...MemberNewsFragment
	}
}

query AllMemberNews($first: IntType = 10, $skip: IntType = 0, $regionId: ItemId) {
	memberNews: allMemberNews(
		filter: { region: { eq: $regionId } }
		orderBy: [createdAt_DESC]
		first: $first
		skip: $skip
	) {
		...MemberNewsLightFragment
	}
	pagination: _allMemberNewsMeta(filter: { region: { eq: $regionId } }) {
		count
	}
}

query AllPastAndFutureMemberNews(
	$regionId: ItemId
	$categoryId: ItemId
	$date: Date
	$first: IntType
	$skip: IntType
) {
	memberNews: allMemberNews(
		filter: {
			region: { eq: $regionId }
			category: { eq: $categoryId }
			OR: [
				{ date: { gt: $date }, dateEnd: { gt: $date, exists: true } }
				{ dateEnd: { lt: $date, exists: true } }
				{ date: { gt: $date } }
			]
		}
		orderBy: [date_DESC]
		first: $first
		skip: $skip
	) {
		...MemberNewsLightFragment
	}
	pagination: _allMemberNewsMeta(
		filter: {
			region: { eq: $regionId }
			category: { eq: $categoryId }
			OR: [
				{ date: { gt: $date }, dateEnd: { gt: $date, exists: true } }
				{ dateEnd: { lt: $date, exists: true } }
				{ date: { gt: $date } }
			]
		}
	) {
		count
	}
}

query AllPresentMemberNews(
	$first: IntType = 100
	$skip: IntType = 0
	$regionId: ItemId
	$date: Date
) {
	presentMemberNews: allMemberNews(
		filter: {
			region: { eq: $regionId }
			date: { lte: $date }
			dateEnd: { gte: $date, exists: true }
		}
		orderBy: [date_DESC]
		first: $first
		skip: $skip
	) {
		...MemberNewsLightFragment
	}
	pagination: _allMemberNewsMeta(
		filter: {
			region: { eq: $regionId }
			date: { lte: $date }
			dateEnd: { gte: $date, exists: true }
		}
	) {
		count
	}
}

query MemberImages($email: String!) {
	member(filter: { email: { matches: { pattern: $email, caseSensitive: false } } }) {
		content {
			... on ImageRecord {
				image {
					...MediaGalleryFragment
				}
				thumb: image {
					...MediaGalleryFragment
				}
			}
		}
	}
	uploads: allUploads(filter: { tags: { anyIn: [$email] } }) {
		...MediaGalleryFragment
	}
	uploadsThumbs: allUploads(filter: { tags: { anyIn: [$email] } }) {
		...MediaGalleryFragment
	}
}

query AllMemberNewsCategories {
	memberNewsCategories: allMemberNewsCategories {
		id
		category
	}
}

query LatestMemberNews($first: IntType = 2, $skip: IntType = 0, $regionId: ItemId) {
	memberNews: allMemberNews(
		filter: { region: { eq: $regionId } }
		orderBy: [createdAt_DESC]
		first: $first
		skip: $skip
	) {
		...MemberNewsLightFragment
	}
}

query RelatedMembers(
	$first: IntType = 6
	$skip: IntType = 0
	$regionId: ItemId
	$memberId: ItemId
) {
	members: allMembers(
		filter: {
			image: { exists: true }
			active: { eq: true }
			region: { eq: $regionId }
			id: { neq: $memberId }
		}
		first: $first
		skip: $skip
	) {
		...MemberLightFragment
	}
}

query MembersList {
	membersList {
		intro(markdown: false)
	}
}

fragment MediaGalleryFragment on FileField {
	_createdAt
	id
	mimeType
	url
	title
	alt
	responsiveImage(imgixParams: { q: 70, auto: format, w: 1000 }) {
		src
		width
		height
		alt
		title
		base64
		bgColor
		sizes
	}
}

fragment MemberFragment on MemberRecord {
	__typename
	_modelApiKey
	id
	firstName
	lastName
	fullName
	email
	bio(markdown: false)
	yearOfBirth
	birthPlace
	city
	webpage
	instagram
	active
	showContact
	memberCategory {
		id
		categoryType
	}
	region {
		...RegionFragment
	}
	image {
		...ImageThumbnailFragment
	}
	content {
		... on ImageRecord {
			__typename
			id
			image {
				...ImageFragment
			}
		}
		... on VideoRecord {
			__typename
			id
			title
			video {
				height
				width
				title
				provider
				providerUid
				thumbnailUrl
				url
			}
		}
		... on RecordInterface {
			__typename
			id
		}
	}
	slug
	resettoken
	_status
	_firstPublishedAt
	_seoMetaTags {
		attributes
		content
		tag
	}
}

fragment MemberLightFragment on MemberRecord {
	__typename
	_modelApiKey
	id
	firstName
	lastName
	fullName
	email
	region {
		...RegionFragment
	}
	image {
		...ImageThumbnailFragment
	}
	slug
	_status
	_firstPublishedAt
}

fragment MemberNewsFragment on MemberNewsRecord {
	__typename
	_modelApiKey
	id
	createdAt
	title
	blackHeadline
	image {
		...ImageFragment
	}
	intro(markdown: false)
	category {
		id
		category
	}
	date
	dateEnd
	location
	slug
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
			}
			... on ButtonRecord {
				__typename
				id
				text
				url
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
			... on FormRecord {
				__typename
				id
				subject
				reciever
				confirmation
				formFields {
					__typename
					... on FormTextRecord {
						id
						title
					}
					... on FormTextblockRecord {
						id
						title
					}
					... on PdfFormRecord {
						id
						title
					}
				}
			}
		}
	}
	region {
		...RegionFragment
	}
	_seoMetaTags {
		attributes
		content
		tag
	}
}

fragment MemberNewsLightFragment on MemberNewsRecord {
	__typename
	_modelApiKey
	id
	createdAt
	title
	image {
		...ImageThumbnailFragment
	}
	intro(markdown: false)
	category {
		id
		category
	}
	date
	dateEnd
	location
	slug
	region {
		...RegionFragment
	}
}
