query AllNews($first: IntType = 10, $skip: IntType = 0, $regionId: ItemId) {
	news: allNews(
		filter: { region: { eq: $regionId } }
		orderBy: [createdAt_DESC]
		first: $first
		skip: $skip
	) {
		...NewsFragment
	}
	pagination: _allNewsMeta(filter: { region: { eq: $regionId } }) {
		count
	}
}

query News($slug: String!) {
	news(filter: { slug: { eq: $slug } }) {
		...NewsFragment
	}
}

query LatestNews($first: IntType = 2, $skip: IntType = 0, $regionId: ItemId) {
	news: allNews(
		filter: { region: { eq: $regionId } }
		orderBy: [createdAt_DESC]
		first: $first
		skip: $skip
	) {
		...NewsFragment
	}
}

fragment NewsFragment on NewsRecord {
	__typename
	_modelApiKey
	id
	title
	slug
	intro
	createdAt
	blackHeadline
	image {
		...ImageFragment
	}
	region {
		...RegionFragment
	}
	content {
		value
		blocks {
			__typename
			... on RelatedMemberNewsRecord {
				id
				memberNews {
					...MemberNewsFragment
				}
			}
			... on ImageRecord {
				id
				image {
					...ImageFragment
				}
			}
			... on RecordInterface {
				id
			}
		}
	}
	_seoMetaTags {
		attributes
		content
		tag
	}
}
