query AllProjects {
	projects: allProjects(orderBy: [title_ASC]) {
		...ProjectFragment
	}
}

query ProjectsIntro {
	introInitiative {
		intro(markdown: false)
	}
}

query LatestProjects($first: IntType = 4, $skip: IntType = 0) {
	projects: allProjects(orderBy: [createdAt_DESC], first: $first, skip: $skip) {
		...ProjectFragment
	}
}

fragment ProjectFragment on ProjectRecord {
	__typename
	_modelApiKey
	title
	image {
		...ImageMediumFragment
	}
	url
	text(markdown: false)
	region {
		...RegionFragment
	}
	_seoMetaTags {
		attributes
		content
		tag
	}
}
