query Region($regionId: ItemId) {
	region(filter: { id: { eq: $regionId } }) {
		__typename
		id
		name
		slug
		contactIntro(markdown: false)
		info {
			text
			title
		}
		gallery {
			id
			headline
			blackText
			image {
				...ImageFragment
			}
			link {
				__typename
				... on CommissionRecord {
					id
					title
					slug
					image {
						...ImageFragment
					}
				}
				... on ForArtistRecord {
					id
					title
					slug
					image {
						...ImageFragment
					}
				}
				... on MemberNewsRecord {
					id
					title
					slug
					image {
						...ImageFragment
					}
				}
				... on NewsRecord {
					id
					title
					slug
					image {
						...ImageFragment
					}
				}
				... on AboutRecord {
					id
					title
					slug
					image {
						...ImageFragment
					}
				}
			}
		}
		sections {
			... on ImageShortcutRecord {
				id
				headline
				text
				blackHeadline
				image {
					...ImageFragment
				}
				link
			}
			... on LatestNewsRecord {
				id
				description
			}
			... on LatestMemberNewsRecord {
				id
			}
			... on TextRecord {
				id
				url
				headline
				text(markdown: false)
			}
			... on SelectedCommissionRecord {
				commissions {
					...CommissionLightFragment
				}
			}
			... on SelectedMemberRecord {
				selectedMembers {
					...MemberLightFragment
				}
			}
		}
	}
}

query RegionMeta($regionId: ItemId) {
	region(filter: { id: { eq: $regionId } }) {
		contactIntro(markdown: false)
		info {
			title
			text
		}
	}
	employees: allEmployees(filter: { region: { eq: $regionId } }, first: 100) {
		name
		email
		title
		region {
			...RegionFragment
			position
			contactIntro(markdown: false)
			info {
				title
				text
			}
		}
	}
	boardmembers: allBoards(filter: { region: { eq: $regionId } }, first: 100) {
		name
		email
		title
		region {
			...RegionFragment
			position
		}
	}
}

fragment RegionFragment on RegionRecord {
	id
	name
	slug
	global
	position
}
