query SiteSearch(
	$memberIds: [ItemId]
	$newsIds: [ItemId]
	$memberNewsIds: [ItemId]
	$first: IntType = 100
	$skip: IntType = 0
) {
	members: allMembers(
		first: $first
		skip: $skip
		filter: { id: { in: $memberIds }, active: { eq: true }, image: { exists: true } }
	) {
		__typename
		_modelApiKey
		title: fullName
		text: bio(markdown: false)
		slug
		image {
			...ImageThumbnailFragment
		}
	}
	news: allNews(first: $first, skip: $skip, filter: { id: { in: $newsIds } }) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
		image {
			...ImageThumbnailFragment
		}
	}
	memberNews: allMemberNews(first: $first, skip: $skip, filter: { id: { in: $memberNewsIds } }) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
		image {
			...ImageThumbnailFragment
		}
	}
}

query SearchMembers(
	$first: IntType = 100
	$skip: IntType = 0
	$memberCategoryIds: [ItemId]
	$regionId: ItemId
) {
	members: allMembers(
		filter: {
			image: { exists: true }
			active: { eq: true }
			region: { eq: $regionId }
			memberCategory: { anyIn: $memberCategoryIds }
		}
		orderBy: _createdAt_DESC
		first: $first
		skip: $skip
	) {
		...MemberLightFragment
	}
	pagination: _allMembersMeta(
		filter: {
			image: { exists: true }
			active: { eq: true }
			region: { eq: $regionId }
			memberCategory: { anyIn: $memberCategoryIds }
		}
	) {
		count
	}
}

query SearchMembersFree($first: IntType = 100, $skip: IntType = 0, $query: String!) {
	members: allMembers(
		first: $first
		skip: $skip
		filter: {
			image: { exists: true }
			active: { eq: true }
			OR: [
				{ firstName: { matches: { pattern: $query, caseSensitive: false } } }
				{ lastName: { matches: { pattern: $query, caseSensitive: false } } }
			]
		}
		orderBy: firstName_ASC
	) {
		...MemberLightFragment
	}
	pagination: _allMembersMeta(
		filter: {
			image: { exists: true }
			active: { eq: true }
			OR: [
				{ firstName: { matches: { pattern: $query, caseSensitive: false } } }
				{ lastName: { matches: { pattern: $query, caseSensitive: false } } }
			]
		}
	) {
		count
	}
}
